source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-flash'
gem 'net-ldap'
gem 'passenger'
gem 'coffee-script'
gem 'slim'
gem 'sass'
gem 'data_mapper'
gem 'sqlite3'
gem 'dm-sqlite-adapter'
gem 'mail'

group :development, :test do
  gem 'capybara'
  gem 'coveralls'
  gem 'guard'
  gem 'guard-compass'
  gem 'guard-rspec'
  gem 'ladle'
  gem 'rspec'
  gem 'shotgun'
  gem 'simplecov'
end
