---
host: localhost
port: 3897
base: dc=example,dc=org
bind_dn: uid=%s,ou=people,dc=example,dc=org # the bind dn should have a %s where the uid goes
admin_bind_dn: uid=admin,ou=people,dc=example,dc=org
admin_password: admin

reset_url: http://localhost:9292/account/reset/%s

mail:
  host: localhost
  port: 2525
  from: help@example.org
